[tool.poetry]
name = "microdata-validator"
version = "0.4.0"
description = "Python package for validating datasets in the microdata platform"
authors = ["microdata-developers"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
jsonschema = "^4.2.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-dotenv = "^0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
